[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix server --include=dev",
  "npm install --prefix client --include=dev"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "cp -r client/dist server/public",
  "npx --prefix server tsc --project server/tsconfig.json",
  "cp server/src/db/schema.sql server/dist/db/schema.sql"
]

[start]
cmd = "node server/dist/index.js"
